# Generated by Django 3.2.23 on 2024-01-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerbloom', '0004_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10, verbose_name='Delivery Charge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_duration',
            field=models.TextField(default=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_info',
            field=models.TextField(default=500),
            preserve_default=False,
        ),
    ]
