# Generated by Django 3.2.23 on 2024-02-04 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowerbloom', '0007_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='flowerbloom.category', verbose_name='Category name'),
        ),
    ]
